/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CultureRouteImport } from './routes/culture'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/events': typeof EventsRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/events': typeof EventsRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/events': typeof EventsRoute
  '/travel': typeof TravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/culture' | '/events' | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/culture' | '/events' | '/travel'
  id: '__root__' | '/' | '/culture' | '/events' | '/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CultureRoute: typeof CultureRoute
  EventsRoute: typeof EventsRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CultureRoute: CultureRoute,
  EventsRoute: EventsRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
